title: Creolie
email: jessica.bourcier@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  La chatterie Creolie vous propose de magnifique et affectueux chats de race Maine Coon
#baseurl: '/creolie' # the subpath of your site, e.g. /blog/
url: "http://creolie.fr" # the base hostname & protocol for your site
#paginate: 10

#gems: [jekyll-paginate]
gems: [jekyll-sitemap, jekyll-seo-tag]

prix: 950
siret: 830 192 472 00017
affixe: De Créolie
CCADDate: 27/11/2016
CCADNum: 2016/9df1-072d
